# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/royal state/PycharmProjects/Tv-Series-And-Movie-Diary/v2.0/MainDesign.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(550, 635)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(280, 0, 271, 591))
        self.stackedWidget.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.stackedWidget.setFrameShape(QtWidgets.QFrame.Box)
        self.stackedWidget.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.stackedWidget.setLineWidth(1)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.label_4 = QtWidgets.QLabel(self.page)
        self.label_4.setGeometry(QtCore.QRect(0, 0, 171, 16))
        self.label_4.setObjectName("label_4")
        self.currentlyWatchingTable = QtWidgets.QTableWidget(self.page)
        self.currentlyWatchingTable.setGeometry(QtCore.QRect(0, 20, 261, 571))
        self.currentlyWatchingTable.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.currentlyWatchingTable.setEditTriggers(QtWidgets.QAbstractItemView.DoubleClicked)
        self.currentlyWatchingTable.setAlternatingRowColors(True)
        self.currentlyWatchingTable.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.currentlyWatchingTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.currentlyWatchingTable.setObjectName("currentlyWatchingTable")
        self.currentlyWatchingTable.setColumnCount(3)
        self.currentlyWatchingTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.currentlyWatchingTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.currentlyWatchingTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.currentlyWatchingTable.setHorizontalHeaderItem(2, item)
        self.currentlyWatchingTable.verticalHeader().setVisible(False)
        self.currentlyWatchingTable.verticalHeader().setDefaultSectionSize(19)
        self.currentlyWatchingTable.verticalHeader().setMinimumSectionSize(15)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.completedTvShowsTable = QtWidgets.QTableWidget(self.page_2)
        self.completedTvShowsTable.setGeometry(QtCore.QRect(0, 20, 261, 571))
        self.completedTvShowsTable.setMinimumSize(QtCore.QSize(261, 571))
        self.completedTvShowsTable.setEditTriggers(QtWidgets.QAbstractItemView.DoubleClicked)
        self.completedTvShowsTable.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.completedTvShowsTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.completedTvShowsTable.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.completedTvShowsTable.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.completedTvShowsTable.setShowGrid(False)
        self.completedTvShowsTable.setWordWrap(False)
        self.completedTvShowsTable.setObjectName("completedTvShowsTable")
        self.completedTvShowsTable.setColumnCount(4)
        self.completedTvShowsTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.completedTvShowsTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.completedTvShowsTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.completedTvShowsTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.completedTvShowsTable.setHorizontalHeaderItem(3, item)
        self.completedTvShowsTable.verticalHeader().setVisible(False)
        self.completedTvShowsTable.verticalHeader().setDefaultSectionSize(19)
        self.completedTvShowsTable.verticalHeader().setMinimumSectionSize(15)
        self.label_3 = QtWidgets.QLabel(self.page_2)
        self.label_3.setGeometry(QtCore.QRect(0, 0, 171, 16))
        self.label_3.setObjectName("label_3")
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.label_5 = QtWidgets.QLabel(self.page_3)
        self.label_5.setGeometry(QtCore.QRect(0, 0, 171, 16))
        self.label_5.setObjectName("label_5")
        self.onBreakTable = QtWidgets.QTableWidget(self.page_3)
        self.onBreakTable.setGeometry(QtCore.QRect(0, 20, 261, 571))
        self.onBreakTable.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.onBreakTable.setEditTriggers(QtWidgets.QAbstractItemView.DoubleClicked)
        self.onBreakTable.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.onBreakTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.onBreakTable.setObjectName("onBreakTable")
        self.onBreakTable.setColumnCount(4)
        self.onBreakTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.onBreakTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.onBreakTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.onBreakTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.onBreakTable.setHorizontalHeaderItem(3, item)
        self.onBreakTable.verticalHeader().setVisible(False)
        self.onBreakTable.verticalHeader().setDefaultSectionSize(19)
        self.onBreakTable.verticalHeader().setMinimumSectionSize(15)
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.label_6 = QtWidgets.QLabel(self.page_4)
        self.label_6.setGeometry(QtCore.QRect(0, 0, 171, 16))
        self.label_6.setObjectName("label_6")
        self.wishListTable = QtWidgets.QTableWidget(self.page_4)
        self.wishListTable.setGeometry(QtCore.QRect(0, 20, 261, 571))
        self.wishListTable.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.wishListTable.setEditTriggers(QtWidgets.QAbstractItemView.DoubleClicked)
        self.wishListTable.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.wishListTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.wishListTable.setObjectName("wishListTable")
        self.wishListTable.setColumnCount(3)
        self.wishListTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.wishListTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.wishListTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.wishListTable.setHorizontalHeaderItem(2, item)
        self.wishListTable.horizontalHeader().setSortIndicatorShown(True)
        self.wishListTable.verticalHeader().setVisible(False)
        self.wishListTable.verticalHeader().setDefaultSectionSize(19)
        self.wishListTable.verticalHeader().setMinimumSectionSize(15)
        self.stackedWidget.addWidget(self.page_4)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.label_7 = QtWidgets.QLabel(self.page_5)
        self.label_7.setGeometry(QtCore.QRect(0, 0, 171, 16))
        self.label_7.setObjectName("label_7")
        self.seenMoviesTable = QtWidgets.QTableWidget(self.page_5)
        self.seenMoviesTable.setGeometry(QtCore.QRect(0, 20, 261, 571))
        self.seenMoviesTable.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.seenMoviesTable.setEditTriggers(QtWidgets.QAbstractItemView.DoubleClicked)
        self.seenMoviesTable.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.seenMoviesTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.seenMoviesTable.setObjectName("seenMoviesTable")
        self.seenMoviesTable.setColumnCount(2)
        self.seenMoviesTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.seenMoviesTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.seenMoviesTable.setHorizontalHeaderItem(1, item)
        self.seenMoviesTable.verticalHeader().setVisible(False)
        self.seenMoviesTable.verticalHeader().setDefaultSectionSize(19)
        self.seenMoviesTable.verticalHeader().setMinimumSectionSize(15)
        self.stackedWidget.addWidget(self.page_5)
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")
        self.label_9 = QtWidgets.QLabel(self.page_6)
        self.label_9.setGeometry(QtCore.QRect(0, 0, 171, 16))
        self.label_9.setObjectName("label_9")
        self.pushButton_3 = QtWidgets.QPushButton(self.page_6)
        self.pushButton_3.setGeometry(QtCore.QRect(90, 560, 171, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        self.resutlTextBrowser = QtWidgets.QTextBrowser(self.page_6)
        self.resutlTextBrowser.setGeometry(QtCore.QRect(0, 20, 265, 537))
        self.resutlTextBrowser.setObjectName("resutlTextBrowser")
        self.stackedWidget.addWidget(self.page_6)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 240, 261, 351))
        self.groupBox.setObjectName("groupBox")
        self.previewBoxGraphicsView = QtWidgets.QGraphicsView(self.groupBox)
        self.previewBoxGraphicsView.setGeometry(QtCore.QRect(2, 15, 257, 333))
        self.previewBoxGraphicsView.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.previewBoxGraphicsView.setObjectName("previewBoxGraphicsView")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 71, 16))
        self.label.setObjectName("label")
        self.loginStatusLabel = QtWidgets.QLabel(self.centralwidget)
        self.loginStatusLabel.setGeometry(QtCore.QRect(90, 10, 101, 16))
        self.loginStatusLabel.setStyleSheet("color: rgb(255, 0, 0);")
        self.loginStatusLabel.setLineWidth(5)
        self.loginStatusLabel.setMidLineWidth(6)
        self.loginStatusLabel.setObjectName("loginStatusLabel")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 40, 261, 131))
        self.groupBox_2.setStyleSheet("font: 75 10pt \"MS Shell Dlg 2\";")
        self.groupBox_2.setObjectName("groupBox_2")
        self.searchTitleEntry = QtWidgets.QLineEdit(self.groupBox_2)
        self.searchTitleEntry.setGeometry(QtCore.QRect(10, 20, 231, 20))
        self.searchTitleEntry.setObjectName("searchTitleEntry")
        self.searchButton = QtWidgets.QPushButton(self.groupBox_2)
        self.searchButton.setGeometry(QtCore.QRect(10, 90, 101, 31))
        self.searchButton.setObjectName("searchButton")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 50, 191, 31))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_8 = QtWidgets.QLabel(self.layoutWidget)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout.addWidget(self.label_8)
        self.searchSourceLocalCheck = QtWidgets.QRadioButton(self.layoutWidget)
        self.searchSourceLocalCheck.setChecked(True)
        self.searchSourceLocalCheck.setObjectName("searchSourceLocalCheck")
        self.horizontalLayout.addWidget(self.searchSourceLocalCheck)
        self.searchSourceOnlineCheck = QtWidgets.QRadioButton(self.layoutWidget)
        self.searchSourceOnlineCheck.setObjectName("searchSourceOnlineCheck")
        self.horizontalLayout.addWidget(self.searchSourceOnlineCheck)
        self.searchStatusLabel = QtWidgets.QLabel(self.groupBox_2)
        self.searchStatusLabel.setGeometry(QtCore.QRect(120, 100, 131, 20))
        self.searchStatusLabel.setText("")
        self.searchStatusLabel.setWordWrap(True)
        self.searchStatusLabel.setObjectName("searchStatusLabel")
        self.addNewEntryButton = QtWidgets.QPushButton(self.centralwidget)
        self.addNewEntryButton.setGeometry(QtCore.QRect(60, 190, 161, 31))
        self.addNewEntryButton.setObjectName("addNewEntryButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 550, 21))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menuDownload_Sites = QtWidgets.QMenu(self.menuFile)
        self.menuDownload_Sites.setObjectName("menuDownload_Sites")
        self.menuWatch_Sites = QtWidgets.QMenu(self.menuFile)
        self.menuWatch_Sites.setObjectName("menuWatch_Sites")
        self.menuOptions = QtWidgets.QMenu(self.menuBar)
        self.menuOptions.setObjectName("menuOptions")
        self.menuView = QtWidgets.QMenu(self.menuBar)
        self.menuView.setObjectName("menuView")
        self.menuCurent_Table = QtWidgets.QMenu(self.menuView)
        self.menuCurent_Table.setSeparatorsCollapsible(True)
        self.menuCurent_Table.setObjectName("menuCurent_Table")
        self.menuHelp = QtWidgets.QMenu(self.menuBar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menuBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actionPush_My_Data = QtWidgets.QAction(MainWindow)
        self.actionPush_My_Data.setObjectName("actionPush_My_Data")
        self.actionPull_My_Data = QtWidgets.QAction(MainWindow)
        self.actionPull_My_Data.setObjectName("actionPull_My_Data")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionUpdate_List = QtWidgets.QAction(MainWindow)
        self.actionUpdate_List.setObjectName("actionUpdate_List")
        self.actionLogin = QtWidgets.QAction(MainWindow)
        self.actionLogin.setObjectName("actionLogin")
        self.actionLogout = QtWidgets.QAction(MainWindow)
        self.actionLogout.setObjectName("actionLogout")
        self.actionCreate_Account = QtWidgets.QAction(MainWindow)
        self.actionCreate_Account.setObjectName("actionCreate_Account")
        self.actionAdd_To_Wish_List = QtWidgets.QAction(MainWindow)
        self.actionAdd_To_Wish_List.setObjectName("actionAdd_To_Wish_List")
        self.actionOnline_Thumbnails = QtWidgets.QAction(MainWindow)
        self.actionOnline_Thumbnails.setObjectName("actionOnline_Thumbnails")
        self.actionAdd_Title = QtWidgets.QAction(MainWindow)
        self.actionAdd_Title.setObjectName("actionAdd_Title")
        self.actionClear_All_Data = QtWidgets.QAction(MainWindow)
        self.actionClear_All_Data.setObjectName("actionClear_All_Data")
        self.actionCurrently_Watching = QtWidgets.QAction(MainWindow)
        self.actionCurrently_Watching.setCheckable(True)
        self.actionCurrently_Watching.setChecked(True)
        self.actionCurrently_Watching.setObjectName("actionCurrently_Watching")
        self.actionComplete_Tv_Shows = QtWidgets.QAction(MainWindow)
        self.actionComplete_Tv_Shows.setCheckable(True)
        self.actionComplete_Tv_Shows.setObjectName("actionComplete_Tv_Shows")
        self.actionWish_List = QtWidgets.QAction(MainWindow)
        self.actionWish_List.setCheckable(True)
        self.actionWish_List.setObjectName("actionWish_List")
        self.actionSeen_Movies = QtWidgets.QAction(MainWindow)
        self.actionSeen_Movies.setCheckable(True)
        self.actionSeen_Movies.setObjectName("actionSeen_Movies")
        self.actionVideo_Tutorials = QtWidgets.QAction(MainWindow)
        self.actionVideo_Tutorials.setObjectName("actionVideo_Tutorials")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionEdit_Sites = QtWidgets.QAction(MainWindow)
        self.actionEdit_Sites.setObjectName("actionEdit_Sites")
        self.actionEZTV = QtWidgets.QAction(MainWindow)
        self.actionEZTV.setObjectName("actionEZTV")
        self.actionPutlocker = QtWidgets.QAction(MainWindow)
        self.actionPutlocker.setObjectName("actionPutlocker")
        self.actionIO_Movies = QtWidgets.QAction(MainWindow)
        self.actionIO_Movies.setObjectName("actionIO_Movies")
        self.action9_Anime = QtWidgets.QAction(MainWindow)
        self.action9_Anime.setObjectName("action9_Anime")
        self.actionPirates_Bay = QtWidgets.QAction(MainWindow)
        self.actionPirates_Bay.setObjectName("actionPirates_Bay")
        self.actionYIFI_Movies = QtWidgets.QAction(MainWindow)
        self.actionYIFI_Movies.setObjectName("actionYIFI_Movies")
        self.actionTorentCouch = QtWidgets.QAction(MainWindow)
        self.actionTorentCouch.setObjectName("actionTorentCouch")
        self.actionEZTV_2 = QtWidgets.QAction(MainWindow)
        self.actionEZTV_2.setObjectName("actionEZTV_2")
        self.actionShows_on_Break = QtWidgets.QAction(MainWindow)
        self.actionShows_on_Break.setCheckable(True)
        self.actionShows_on_Break.setObjectName("actionShows_on_Break")
        self.actionSearch_Results_Tab = QtWidgets.QAction(MainWindow)
        self.actionSearch_Results_Tab.setCheckable(True)
        self.actionSearch_Results_Tab.setObjectName("actionSearch_Results_Tab")
        self.actionBuck_Up_My_Data = QtWidgets.QAction(MainWindow)
        self.actionBuck_Up_My_Data.setObjectName("actionBuck_Up_My_Data")
        self.actionRecover_My_Data_from_A_Buckup = QtWidgets.QAction(MainWindow)
        self.actionRecover_My_Data_from_A_Buckup.setObjectName("actionRecover_My_Data_from_A_Buckup")
        self.actionUpdate_Local_Search_List = QtWidgets.QAction(MainWindow)
        self.actionUpdate_Local_Search_List.setObjectName("actionUpdate_Local_Search_List")
        self.actionUpdate = QtWidgets.QAction(MainWindow)
        self.actionUpdate.setObjectName("actionUpdate")
        self.menuFile.addAction(self.actionPush_My_Data)
        self.menuFile.addAction(self.actionPull_My_Data)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionBuck_Up_My_Data)
        self.menuFile.addAction(self.actionRecover_My_Data_from_A_Buckup)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.menuWatch_Sites.menuAction())
        self.menuFile.addAction(self.menuDownload_Sites.menuAction())
        self.menuFile.addAction(self.actionEdit_Sites)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuOptions.addAction(self.actionUpdate_List)
        self.menuOptions.addSeparator()
        self.menuOptions.addAction(self.actionLogin)
        self.menuOptions.addAction(self.actionLogout)
        self.menuOptions.addAction(self.actionCreate_Account)
        self.menuOptions.addSeparator()
        self.menuOptions.addAction(self.actionAdd_To_Wish_List)
        self.menuOptions.addAction(self.actionAdd_Title)
        self.menuOptions.addSeparator()
        self.menuOptions.addAction(self.actionOnline_Thumbnails)
        self.menuOptions.addAction(self.actionClear_All_Data)
        self.menuOptions.addAction(self.actionUpdate_Local_Search_List)
        self.menuCurent_Table.addAction(self.actionCurrently_Watching)
        self.menuCurent_Table.addAction(self.actionComplete_Tv_Shows)
        self.menuCurent_Table.addAction(self.actionShows_on_Break)
        self.menuCurent_Table.addAction(self.actionWish_List)
        self.menuCurent_Table.addAction(self.actionSeen_Movies)
        self.menuCurent_Table.addSeparator()
        self.menuCurent_Table.addAction(self.actionSearch_Results_Tab)
        self.menuView.addAction(self.menuCurent_Table.menuAction())
        self.menuHelp.addAction(self.actionVideo_Tutorials)
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionUpdate)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuOptions.menuAction())
        self.menuBar.addAction(self.menuView.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.currentlyWatchingTable, self.completedTvShowsTable)
        MainWindow.setTabOrder(self.completedTvShowsTable, self.onBreakTable)
        MainWindow.setTabOrder(self.onBreakTable, self.wishListTable)
        MainWindow.setTabOrder(self.wishListTable, self.seenMoviesTable)
        MainWindow.setTabOrder(self.seenMoviesTable, self.pushButton_3)
        MainWindow.setTabOrder(self.pushButton_3, self.searchTitleEntry)
        MainWindow.setTabOrder(self.searchTitleEntry, self.searchButton)
        MainWindow.setTabOrder(self.searchButton, self.searchSourceLocalCheck)
        MainWindow.setTabOrder(self.searchSourceLocalCheck, self.searchSourceOnlineCheck)
        MainWindow.setTabOrder(self.searchSourceOnlineCheck, self.addNewEntryButton)
        MainWindow.setTabOrder(self.addNewEntryButton, self.previewBoxGraphicsView)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_4.setText(_translate("MainWindow", " Currently Watching TV Shows : 1"))
        item = self.currentlyWatchingTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Title"))
        item = self.currentlyWatchingTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Se"))
        item = self.currentlyWatchingTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Ep"))
        self.completedTvShowsTable.setSortingEnabled(True)
        item = self.completedTvShowsTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Title"))
        item = self.completedTvShowsTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Se"))
        item = self.completedTvShowsTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Ep"))
        item = self.completedTvShowsTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Complete date"))
        self.label_3.setText(_translate("MainWindow", " Complete TV Shows : 2"))
        self.label_5.setText(_translate("MainWindow", " Tv Shows on Break : 3"))
        item = self.onBreakTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Title"))
        item = self.onBreakTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Se"))
        item = self.onBreakTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Ep"))
        item = self.onBreakTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Date Braked"))
        self.label_6.setText(_translate("MainWindow", " Wish List : 4"))
        self.wishListTable.setSortingEnabled(True)
        item = self.wishListTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Title"))
        item = self.wishListTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Type"))
        item = self.wishListTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Date added"))
        self.label_7.setText(_translate("MainWindow", " Seen Movies : 5"))
        item = self.seenMoviesTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Title"))
        item = self.seenMoviesTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Date Seen"))
        self.label_9.setText(_translate("MainWindow", "Search Resalts : 6"))
        self.pushButton_3.setText(_translate("MainWindow", "View More info On Your Browser"))
        self.groupBox.setTitle(_translate("MainWindow", "PREVIW BOX "))
        self.label.setText(_translate("MainWindow", "Login Status: "))
        self.loginStatusLabel.setStatusTip(_translate("MainWindow", "Connection status"))
        self.loginStatusLabel.setText(_translate("MainWindow", " NOT LOGGED ON"))
        self.groupBox_2.setTitle(_translate("MainWindow", "SEARCH : "))
        self.searchTitleEntry.setPlaceholderText(_translate("MainWindow", " Title"))
        self.searchButton.setText(_translate("MainWindow", "Search"))
        self.label_8.setText(_translate("MainWindow", "Source : "))
        self.searchSourceLocalCheck.setText(_translate("MainWindow", "Local"))
        self.searchSourceOnlineCheck.setText(_translate("MainWindow", "Online"))
        self.addNewEntryButton.setText(_translate("MainWindow", "ADD A NEW TITLE..."))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuDownload_Sites.setTitle(_translate("MainWindow", "Download Sites"))
        self.menuWatch_Sites.setTitle(_translate("MainWindow", "Watch Sites"))
        self.menuOptions.setTitle(_translate("MainWindow", "Options "))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.menuCurent_Table.setTitle(_translate("MainWindow", "Curent Table : "))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionPush_My_Data.setText(_translate("MainWindow", "Push My Data"))
        self.actionPull_My_Data.setText(_translate("MainWindow", "Pull My Data"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionUpdate_List.setText(_translate("MainWindow", "Update List"))
        self.actionLogin.setText(_translate("MainWindow", "Login"))
        self.actionLogout.setText(_translate("MainWindow", "Logout"))
        self.actionCreate_Account.setText(_translate("MainWindow", "Create Account"))
        self.actionAdd_To_Wish_List.setText(_translate("MainWindow", "Add To Wish List"))
        self.actionOnline_Thumbnails.setText(_translate("MainWindow", "Online Thumbnails"))
        self.actionAdd_Title.setText(_translate("MainWindow", "Add New Title"))
        self.actionAdd_Title.setShortcut(_translate("MainWindow", "F5"))
        self.actionClear_All_Data.setText(_translate("MainWindow", "Clear All Data"))
        self.actionCurrently_Watching.setText(_translate("MainWindow", "Currently Watching"))
        self.actionCurrently_Watching.setShortcut(_translate("MainWindow", "Alt+1"))
        self.actionComplete_Tv_Shows.setText(_translate("MainWindow", "Complete Tv Shows"))
        self.actionComplete_Tv_Shows.setShortcut(_translate("MainWindow", "Alt+2"))
        self.actionWish_List.setText(_translate("MainWindow", "Wish List"))
        self.actionWish_List.setShortcut(_translate("MainWindow", "Alt+4"))
        self.actionSeen_Movies.setText(_translate("MainWindow", "Seen Movies"))
        self.actionSeen_Movies.setShortcut(_translate("MainWindow", "Alt+5"))
        self.actionVideo_Tutorials.setText(_translate("MainWindow", "Video Tutorials"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionEdit_Sites.setText(_translate("MainWindow", "Edit Sites"))
        self.actionEZTV.setText(_translate("MainWindow", "Fmovies"))
        self.actionPutlocker.setText(_translate("MainWindow", "Putlocker"))
        self.actionIO_Movies.setText(_translate("MainWindow", "IO-Movies"))
        self.action9_Anime.setText(_translate("MainWindow", "9-Anime"))
        self.actionPirates_Bay.setText(_translate("MainWindow", "Pirates Bay"))
        self.actionYIFI_Movies.setText(_translate("MainWindow", "YIFI Movies"))
        self.actionTorentCouch.setText(_translate("MainWindow", "TorentCouch"))
        self.actionEZTV_2.setText(_translate("MainWindow", "EZTV"))
        self.actionShows_on_Break.setText(_translate("MainWindow", "Shows on Break"))
        self.actionShows_on_Break.setShortcut(_translate("MainWindow", "Alt+3"))
        self.actionSearch_Results_Tab.setText(_translate("MainWindow", "Search Results Tab"))
        self.actionSearch_Results_Tab.setShortcut(_translate("MainWindow", "Alt+6"))
        self.actionBuck_Up_My_Data.setText(_translate("MainWindow", "Buck Up My Data"))
        self.actionRecover_My_Data_from_A_Buckup.setText(_translate("MainWindow", "Load Data from A Buckup"))
        self.actionUpdate_Local_Search_List.setText(_translate("MainWindow", "Update Local Search List"))
        self.actionUpdate.setText(_translate("MainWindow", "Update"))
