# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/ayieko/Projects And  Research/PycharmProjects/Tv-Series-And-Movie-Diary/v2.0/MainDesign.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(550, 635)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.stackedWidget = QtGui.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(280, 0, 271, 591))
        self.stackedWidget.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.stackedWidget.setFrameShape(QtGui.QFrame.Box)
        self.stackedWidget.setFrameShadow(QtGui.QFrame.Sunken)
        self.stackedWidget.setLineWidth(1)
        self.stackedWidget.setObjectName(_fromUtf8("stackedWidget"))
        self.page = QtGui.QWidget()
        self.page.setObjectName(_fromUtf8("page"))
        self.label_4 = QtGui.QLabel(self.page)
        self.label_4.setGeometry(QtCore.QRect(0, 0, 171, 16))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.currentlyWatchingTable = QtGui.QTableWidget(self.page)
        self.currentlyWatchingTable.setGeometry(QtCore.QRect(0, 20, 261, 571))
        self.currentlyWatchingTable.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.currentlyWatchingTable.setEditTriggers(QtGui.QAbstractItemView.DoubleClicked)
        self.currentlyWatchingTable.setAlternatingRowColors(True)
        self.currentlyWatchingTable.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.currentlyWatchingTable.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.currentlyWatchingTable.setObjectName(_fromUtf8("currentlyWatchingTable"))
        self.currentlyWatchingTable.setColumnCount(3)
        self.currentlyWatchingTable.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.currentlyWatchingTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.currentlyWatchingTable.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.currentlyWatchingTable.setHorizontalHeaderItem(2, item)
        self.currentlyWatchingTable.verticalHeader().setVisible(False)
        self.currentlyWatchingTable.verticalHeader().setDefaultSectionSize(19)
        self.currentlyWatchingTable.verticalHeader().setMinimumSectionSize(15)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtGui.QWidget()
        self.page_2.setObjectName(_fromUtf8("page_2"))
        self.completedTvShowsTable = QtGui.QTableWidget(self.page_2)
        self.completedTvShowsTable.setGeometry(QtCore.QRect(0, 20, 261, 571))
        self.completedTvShowsTable.setMinimumSize(QtCore.QSize(261, 571))
        self.completedTvShowsTable.setEditTriggers(QtGui.QAbstractItemView.DoubleClicked)
        self.completedTvShowsTable.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.completedTvShowsTable.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.completedTvShowsTable.setVerticalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.completedTvShowsTable.setHorizontalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.completedTvShowsTable.setShowGrid(False)
        self.completedTvShowsTable.setWordWrap(False)
        self.completedTvShowsTable.setObjectName(_fromUtf8("completedTvShowsTable"))
        self.completedTvShowsTable.setColumnCount(4)
        self.completedTvShowsTable.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.completedTvShowsTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.completedTvShowsTable.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.completedTvShowsTable.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.completedTvShowsTable.setHorizontalHeaderItem(3, item)
        self.completedTvShowsTable.verticalHeader().setVisible(False)
        self.completedTvShowsTable.verticalHeader().setDefaultSectionSize(19)
        self.completedTvShowsTable.verticalHeader().setMinimumSectionSize(15)
        self.label_3 = QtGui.QLabel(self.page_2)
        self.label_3.setGeometry(QtCore.QRect(0, 0, 171, 16))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtGui.QWidget()
        self.page_3.setObjectName(_fromUtf8("page_3"))
        self.label_5 = QtGui.QLabel(self.page_3)
        self.label_5.setGeometry(QtCore.QRect(0, 0, 171, 16))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.onBreakTable = QtGui.QTableWidget(self.page_3)
        self.onBreakTable.setGeometry(QtCore.QRect(0, 20, 261, 571))
        self.onBreakTable.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.onBreakTable.setEditTriggers(QtGui.QAbstractItemView.DoubleClicked)
        self.onBreakTable.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.onBreakTable.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.onBreakTable.setObjectName(_fromUtf8("onBreakTable"))
        self.onBreakTable.setColumnCount(4)
        self.onBreakTable.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.onBreakTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.onBreakTable.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.onBreakTable.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.onBreakTable.setHorizontalHeaderItem(3, item)
        self.onBreakTable.verticalHeader().setVisible(False)
        self.onBreakTable.verticalHeader().setDefaultSectionSize(19)
        self.onBreakTable.verticalHeader().setMinimumSectionSize(15)
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtGui.QWidget()
        self.page_4.setObjectName(_fromUtf8("page_4"))
        self.label_6 = QtGui.QLabel(self.page_4)
        self.label_6.setGeometry(QtCore.QRect(0, 0, 171, 16))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.wishListTable = QtGui.QTableWidget(self.page_4)
        self.wishListTable.setGeometry(QtCore.QRect(0, 20, 261, 571))
        self.wishListTable.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.wishListTable.setEditTriggers(QtGui.QAbstractItemView.DoubleClicked)
        self.wishListTable.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.wishListTable.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.wishListTable.setObjectName(_fromUtf8("wishListTable"))
        self.wishListTable.setColumnCount(3)
        self.wishListTable.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.wishListTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.wishListTable.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.wishListTable.setHorizontalHeaderItem(2, item)
        self.wishListTable.horizontalHeader().setSortIndicatorShown(True)
        self.wishListTable.verticalHeader().setVisible(False)
        self.wishListTable.verticalHeader().setDefaultSectionSize(19)
        self.wishListTable.verticalHeader().setMinimumSectionSize(15)
        self.stackedWidget.addWidget(self.page_4)
        self.page_5 = QtGui.QWidget()
        self.page_5.setObjectName(_fromUtf8("page_5"))
        self.label_7 = QtGui.QLabel(self.page_5)
        self.label_7.setGeometry(QtCore.QRect(0, 0, 171, 16))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.seenMoviesTable = QtGui.QTableWidget(self.page_5)
        self.seenMoviesTable.setGeometry(QtCore.QRect(0, 20, 261, 571))
        self.seenMoviesTable.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.seenMoviesTable.setEditTriggers(QtGui.QAbstractItemView.DoubleClicked)
        self.seenMoviesTable.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.seenMoviesTable.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.seenMoviesTable.setObjectName(_fromUtf8("seenMoviesTable"))
        self.seenMoviesTable.setColumnCount(2)
        self.seenMoviesTable.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.seenMoviesTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.seenMoviesTable.setHorizontalHeaderItem(1, item)
        self.seenMoviesTable.verticalHeader().setVisible(False)
        self.seenMoviesTable.verticalHeader().setDefaultSectionSize(19)
        self.seenMoviesTable.verticalHeader().setMinimumSectionSize(15)
        self.stackedWidget.addWidget(self.page_5)
        self.page_6 = QtGui.QWidget()
        self.page_6.setObjectName(_fromUtf8("page_6"))
        self.label_9 = QtGui.QLabel(self.page_6)
        self.label_9.setGeometry(QtCore.QRect(0, 0, 171, 16))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.pushButton_3 = QtGui.QPushButton(self.page_6)
        self.pushButton_3.setGeometry(QtCore.QRect(90, 560, 171, 23))
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.resutlTextBrowser = QtGui.QTextBrowser(self.page_6)
        self.resutlTextBrowser.setGeometry(QtCore.QRect(0, 20, 265, 537))
        self.resutlTextBrowser.setObjectName(_fromUtf8("resutlTextBrowser"))
        self.stackedWidget.addWidget(self.page_6)
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 240, 261, 351))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.previewBoxGraphicsView = QtGui.QGraphicsView(self.groupBox)
        self.previewBoxGraphicsView.setGeometry(QtCore.QRect(2, 15, 257, 333))
        self.previewBoxGraphicsView.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.previewBoxGraphicsView.setObjectName(_fromUtf8("previewBoxGraphicsView"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 71, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.loginStatusLabel = QtGui.QLabel(self.centralwidget)
        self.loginStatusLabel.setGeometry(QtCore.QRect(90, 10, 101, 16))
        self.loginStatusLabel.setStyleSheet(_fromUtf8("color: rgb(255, 0, 0);"))
        self.loginStatusLabel.setLineWidth(5)
        self.loginStatusLabel.setMidLineWidth(6)
        self.loginStatusLabel.setObjectName(_fromUtf8("loginStatusLabel"))
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 40, 261, 131))
        self.groupBox_2.setStyleSheet(_fromUtf8("font: 75 10pt \"MS Shell Dlg 2\";"))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.searchTitleEntry = QtGui.QLineEdit(self.groupBox_2)
        self.searchTitleEntry.setGeometry(QtCore.QRect(10, 20, 231, 20))
        self.searchTitleEntry.setObjectName(_fromUtf8("searchTitleEntry"))
        self.searchButton = QtGui.QPushButton(self.groupBox_2)
        self.searchButton.setGeometry(QtCore.QRect(10, 90, 101, 31))
        self.searchButton.setObjectName(_fromUtf8("searchButton"))
        self.layoutWidget = QtGui.QWidget(self.groupBox_2)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 50, 191, 31))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_8 = QtGui.QLabel(self.layoutWidget)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout.addWidget(self.label_8)
        self.searchSourceLocalCheck = QtGui.QRadioButton(self.layoutWidget)
        self.searchSourceLocalCheck.setChecked(True)
        self.searchSourceLocalCheck.setObjectName(_fromUtf8("searchSourceLocalCheck"))
        self.horizontalLayout.addWidget(self.searchSourceLocalCheck)
        self.searchSourceOnlineCheck = QtGui.QRadioButton(self.layoutWidget)
        self.searchSourceOnlineCheck.setObjectName(_fromUtf8("searchSourceOnlineCheck"))
        self.horizontalLayout.addWidget(self.searchSourceOnlineCheck)
        self.searchStatusLabel = QtGui.QLabel(self.groupBox_2)
        self.searchStatusLabel.setGeometry(QtCore.QRect(120, 100, 131, 20))
        self.searchStatusLabel.setText(_fromUtf8(""))
        self.searchStatusLabel.setWordWrap(True)
        self.searchStatusLabel.setObjectName(_fromUtf8("searchStatusLabel"))
        self.addNewEntryButton = QtGui.QPushButton(self.centralwidget)
        self.addNewEntryButton.setGeometry(QtCore.QRect(60, 190, 161, 31))
        self.addNewEntryButton.setObjectName(_fromUtf8("addNewEntryButton"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 550, 21))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menuFile = QtGui.QMenu(self.menuBar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuDownload_Sites = QtGui.QMenu(self.menuFile)
        self.menuDownload_Sites.setObjectName(_fromUtf8("menuDownload_Sites"))
        self.menuWatch_Sites = QtGui.QMenu(self.menuFile)
        self.menuWatch_Sites.setObjectName(_fromUtf8("menuWatch_Sites"))
        self.menuOptions = QtGui.QMenu(self.menuBar)
        self.menuOptions.setObjectName(_fromUtf8("menuOptions"))
        self.menuView = QtGui.QMenu(self.menuBar)
        self.menuView.setObjectName(_fromUtf8("menuView"))
        self.menuCurent_Table = QtGui.QMenu(self.menuView)
        self.menuCurent_Table.setSeparatorsCollapsible(True)
        self.menuCurent_Table.setObjectName(_fromUtf8("menuCurent_Table"))
        self.menuHelp = QtGui.QMenu(self.menuBar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menuBar)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        MainWindow.setStatusBar(self.statusBar)
        self.actionPush_My_Data = QtGui.QAction(MainWindow)
        self.actionPush_My_Data.setObjectName(_fromUtf8("actionPush_My_Data"))
        self.actionPull_My_Data = QtGui.QAction(MainWindow)
        self.actionPull_My_Data.setObjectName(_fromUtf8("actionPull_My_Data"))
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionUpdate_List = QtGui.QAction(MainWindow)
        self.actionUpdate_List.setObjectName(_fromUtf8("actionUpdate_List"))
        self.actionLogin = QtGui.QAction(MainWindow)
        self.actionLogin.setObjectName(_fromUtf8("actionLogin"))
        self.actionLogout = QtGui.QAction(MainWindow)
        self.actionLogout.setObjectName(_fromUtf8("actionLogout"))
        self.actionCreate_Account = QtGui.QAction(MainWindow)
        self.actionCreate_Account.setObjectName(_fromUtf8("actionCreate_Account"))
        self.actionAdd_To_Wish_List = QtGui.QAction(MainWindow)
        self.actionAdd_To_Wish_List.setObjectName(_fromUtf8("actionAdd_To_Wish_List"))
        self.actionOnline_Thumbnails = QtGui.QAction(MainWindow)
        self.actionOnline_Thumbnails.setObjectName(_fromUtf8("actionOnline_Thumbnails"))
        self.actionAdd_Title = QtGui.QAction(MainWindow)
        self.actionAdd_Title.setObjectName(_fromUtf8("actionAdd_Title"))
        self.actionClear_All_Data = QtGui.QAction(MainWindow)
        self.actionClear_All_Data.setObjectName(_fromUtf8("actionClear_All_Data"))
        self.actionCurrently_Watching = QtGui.QAction(MainWindow)
        self.actionCurrently_Watching.setCheckable(True)
        self.actionCurrently_Watching.setChecked(True)
        self.actionCurrently_Watching.setObjectName(_fromUtf8("actionCurrently_Watching"))
        self.actionComplete_Tv_Shows = QtGui.QAction(MainWindow)
        self.actionComplete_Tv_Shows.setCheckable(True)
        self.actionComplete_Tv_Shows.setObjectName(_fromUtf8("actionComplete_Tv_Shows"))
        self.actionWish_List = QtGui.QAction(MainWindow)
        self.actionWish_List.setCheckable(True)
        self.actionWish_List.setObjectName(_fromUtf8("actionWish_List"))
        self.actionSeen_Movies = QtGui.QAction(MainWindow)
        self.actionSeen_Movies.setCheckable(True)
        self.actionSeen_Movies.setObjectName(_fromUtf8("actionSeen_Movies"))
        self.actionVideo_Tutorials = QtGui.QAction(MainWindow)
        self.actionVideo_Tutorials.setObjectName(_fromUtf8("actionVideo_Tutorials"))
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionEdit_Sites = QtGui.QAction(MainWindow)
        self.actionEdit_Sites.setObjectName(_fromUtf8("actionEdit_Sites"))
        self.actionEZTV = QtGui.QAction(MainWindow)
        self.actionEZTV.setObjectName(_fromUtf8("actionEZTV"))
        self.actionPutlocker = QtGui.QAction(MainWindow)
        self.actionPutlocker.setObjectName(_fromUtf8("actionPutlocker"))
        self.actionIO_Movies = QtGui.QAction(MainWindow)
        self.actionIO_Movies.setObjectName(_fromUtf8("actionIO_Movies"))
        self.action9_Anime = QtGui.QAction(MainWindow)
        self.action9_Anime.setObjectName(_fromUtf8("action9_Anime"))
        self.actionPirates_Bay = QtGui.QAction(MainWindow)
        self.actionPirates_Bay.setObjectName(_fromUtf8("actionPirates_Bay"))
        self.actionYIFI_Movies = QtGui.QAction(MainWindow)
        self.actionYIFI_Movies.setObjectName(_fromUtf8("actionYIFI_Movies"))
        self.actionTorentCouch = QtGui.QAction(MainWindow)
        self.actionTorentCouch.setObjectName(_fromUtf8("actionTorentCouch"))
        self.actionEZTV_2 = QtGui.QAction(MainWindow)
        self.actionEZTV_2.setObjectName(_fromUtf8("actionEZTV_2"))
        self.actionShows_on_Break = QtGui.QAction(MainWindow)
        self.actionShows_on_Break.setCheckable(True)
        self.actionShows_on_Break.setObjectName(_fromUtf8("actionShows_on_Break"))
        self.actionSearch_Results_Tab = QtGui.QAction(MainWindow)
        self.actionSearch_Results_Tab.setCheckable(True)
        self.actionSearch_Results_Tab.setObjectName(_fromUtf8("actionSearch_Results_Tab"))
        self.actionBuck_Up_My_Data = QtGui.QAction(MainWindow)
        self.actionBuck_Up_My_Data.setObjectName(_fromUtf8("actionBuck_Up_My_Data"))
        self.actionRecover_My_Data_from_A_Buckup = QtGui.QAction(MainWindow)
        self.actionRecover_My_Data_from_A_Buckup.setObjectName(_fromUtf8("actionRecover_My_Data_from_A_Buckup"))
        self.actionUpdate_Local_Search_List = QtGui.QAction(MainWindow)
        self.actionUpdate_Local_Search_List.setObjectName(_fromUtf8("actionUpdate_Local_Search_List"))
        self.actionUpdate = QtGui.QAction(MainWindow)
        self.actionUpdate.setObjectName(_fromUtf8("actionUpdate"))
        self.menuFile.addAction(self.actionPush_My_Data)
        self.menuFile.addAction(self.actionPull_My_Data)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionBuck_Up_My_Data)
        self.menuFile.addAction(self.actionRecover_My_Data_from_A_Buckup)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.menuWatch_Sites.menuAction())
        self.menuFile.addAction(self.menuDownload_Sites.menuAction())
        self.menuFile.addAction(self.actionEdit_Sites)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuOptions.addAction(self.actionUpdate_List)
        self.menuOptions.addSeparator()
        self.menuOptions.addAction(self.actionLogin)
        self.menuOptions.addAction(self.actionLogout)
        self.menuOptions.addAction(self.actionCreate_Account)
        self.menuOptions.addSeparator()
        self.menuOptions.addAction(self.actionAdd_To_Wish_List)
        self.menuOptions.addAction(self.actionAdd_Title)
        self.menuOptions.addSeparator()
        self.menuOptions.addAction(self.actionOnline_Thumbnails)
        self.menuOptions.addAction(self.actionClear_All_Data)
        self.menuOptions.addAction(self.actionUpdate_Local_Search_List)
        self.menuCurent_Table.addAction(self.actionCurrently_Watching)
        self.menuCurent_Table.addAction(self.actionComplete_Tv_Shows)
        self.menuCurent_Table.addAction(self.actionShows_on_Break)
        self.menuCurent_Table.addAction(self.actionWish_List)
        self.menuCurent_Table.addAction(self.actionSeen_Movies)
        self.menuCurent_Table.addSeparator()
        self.menuCurent_Table.addAction(self.actionSearch_Results_Tab)
        self.menuView.addAction(self.menuCurent_Table.menuAction())
        self.menuHelp.addAction(self.actionVideo_Tutorials)
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionUpdate)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuOptions.menuAction())
        self.menuBar.addAction(self.menuView.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.currentlyWatchingTable, self.completedTvShowsTable)
        MainWindow.setTabOrder(self.completedTvShowsTable, self.onBreakTable)
        MainWindow.setTabOrder(self.onBreakTable, self.wishListTable)
        MainWindow.setTabOrder(self.wishListTable, self.seenMoviesTable)
        MainWindow.setTabOrder(self.seenMoviesTable, self.pushButton_3)
        MainWindow.setTabOrder(self.pushButton_3, self.searchTitleEntry)
        MainWindow.setTabOrder(self.searchTitleEntry, self.searchButton)
        MainWindow.setTabOrder(self.searchButton, self.searchSourceLocalCheck)
        MainWindow.setTabOrder(self.searchSourceLocalCheck, self.searchSourceOnlineCheck)
        MainWindow.setTabOrder(self.searchSourceOnlineCheck, self.addNewEntryButton)
        MainWindow.setTabOrder(self.addNewEntryButton, self.previewBoxGraphicsView)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.label_4.setText(_translate("MainWindow", " Currently Watching TV Shows : 1", None))
        item = self.currentlyWatchingTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Title", None))
        item = self.currentlyWatchingTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Se", None))
        item = self.currentlyWatchingTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Ep", None))
        self.completedTvShowsTable.setSortingEnabled(True)
        item = self.completedTvShowsTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Title", None))
        item = self.completedTvShowsTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Se", None))
        item = self.completedTvShowsTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Ep", None))
        item = self.completedTvShowsTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Complete date", None))
        self.label_3.setText(_translate("MainWindow", " Complete TV Shows : 2", None))
        self.label_5.setText(_translate("MainWindow", " Tv Shows on Break : 3", None))
        item = self.onBreakTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Title", None))
        item = self.onBreakTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Se", None))
        item = self.onBreakTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Ep", None))
        item = self.onBreakTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Date Braked", None))
        self.label_6.setText(_translate("MainWindow", " Wish List : 4", None))
        self.wishListTable.setSortingEnabled(True)
        item = self.wishListTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Title", None))
        item = self.wishListTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Type", None))
        item = self.wishListTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Date added", None))
        self.label_7.setText(_translate("MainWindow", " Seen Movies : 5", None))
        item = self.seenMoviesTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Title", None))
        item = self.seenMoviesTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Date Seen", None))
        self.label_9.setText(_translate("MainWindow", "Search Resalts : 6", None))
        self.pushButton_3.setText(_translate("MainWindow", "View More info On Your Browser", None))
        self.groupBox.setTitle(_translate("MainWindow", "PREVIW BOX ", None))
        self.label.setText(_translate("MainWindow", "Login Status: ", None))
        self.loginStatusLabel.setStatusTip(_translate("MainWindow", "Connection status", None))
        self.loginStatusLabel.setText(_translate("MainWindow", " NOT LOGGED ON", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "SEARCH : ", None))
        self.searchTitleEntry.setPlaceholderText(_translate("MainWindow", " Title", None))
        self.searchButton.setText(_translate("MainWindow", "Search", None))
        self.label_8.setText(_translate("MainWindow", "Source : ", None))
        self.searchSourceLocalCheck.setText(_translate("MainWindow", "Local", None))
        self.searchSourceOnlineCheck.setText(_translate("MainWindow", "Online", None))
        self.addNewEntryButton.setText(_translate("MainWindow", "ADD A NEW TITLE...", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuDownload_Sites.setTitle(_translate("MainWindow", "Download Sites", None))
        self.menuWatch_Sites.setTitle(_translate("MainWindow", "Watch Sites", None))
        self.menuOptions.setTitle(_translate("MainWindow", "Options ", None))
        self.menuView.setTitle(_translate("MainWindow", "View", None))
        self.menuCurent_Table.setTitle(_translate("MainWindow", "Curent Table : ", None))
        self.menuHelp.setTitle(_translate("MainWindow", "Help", None))
        self.actionPush_My_Data.setText(_translate("MainWindow", "Push My Data", None))
        self.actionPull_My_Data.setText(_translate("MainWindow", "Pull My Data", None))
        self.actionExit.setText(_translate("MainWindow", "Exit", None))
        self.actionUpdate_List.setText(_translate("MainWindow", "Update List", None))
        self.actionLogin.setText(_translate("MainWindow", "Login", None))
        self.actionLogout.setText(_translate("MainWindow", "Logout", None))
        self.actionCreate_Account.setText(_translate("MainWindow", "Create Account", None))
        self.actionAdd_To_Wish_List.setText(_translate("MainWindow", "Add To Wish List", None))
        self.actionOnline_Thumbnails.setText(_translate("MainWindow", "Online Thumbnails", None))
        self.actionAdd_Title.setText(_translate("MainWindow", "Add New Title", None))
        self.actionAdd_Title.setShortcut(_translate("MainWindow", "F5", None))
        self.actionClear_All_Data.setText(_translate("MainWindow", "Clear All Data", None))
        self.actionCurrently_Watching.setText(_translate("MainWindow", "Currently Watching", None))
        self.actionCurrently_Watching.setShortcut(_translate("MainWindow", "Alt+1", None))
        self.actionComplete_Tv_Shows.setText(_translate("MainWindow", "Complete Tv Shows", None))
        self.actionComplete_Tv_Shows.setShortcut(_translate("MainWindow", "Alt+2", None))
        self.actionWish_List.setText(_translate("MainWindow", "Wish List", None))
        self.actionWish_List.setShortcut(_translate("MainWindow", "Alt+4", None))
        self.actionSeen_Movies.setText(_translate("MainWindow", "Seen Movies", None))
        self.actionSeen_Movies.setShortcut(_translate("MainWindow", "Alt+5", None))
        self.actionVideo_Tutorials.setText(_translate("MainWindow", "Video Tutorials", None))
        self.actionAbout.setText(_translate("MainWindow", "About", None))
        self.actionEdit_Sites.setText(_translate("MainWindow", "Edit Sites", None))
        self.actionEZTV.setText(_translate("MainWindow", "Fmovies", None))
        self.actionPutlocker.setText(_translate("MainWindow", "Putlocker", None))
        self.actionIO_Movies.setText(_translate("MainWindow", "IO-Movies", None))
        self.action9_Anime.setText(_translate("MainWindow", "9-Anime", None))
        self.actionPirates_Bay.setText(_translate("MainWindow", "Pirates Bay", None))
        self.actionYIFI_Movies.setText(_translate("MainWindow", "YIFI Movies", None))
        self.actionTorentCouch.setText(_translate("MainWindow", "TorentCouch", None))
        self.actionEZTV_2.setText(_translate("MainWindow", "EZTV", None))
        self.actionShows_on_Break.setText(_translate("MainWindow", "Shows on Break", None))
        self.actionShows_on_Break.setShortcut(_translate("MainWindow", "Alt+3", None))
        self.actionSearch_Results_Tab.setText(_translate("MainWindow", "Search Results Tab", None))
        self.actionSearch_Results_Tab.setShortcut(_translate("MainWindow", "Alt+6", None))
        self.actionBuck_Up_My_Data.setText(_translate("MainWindow", "Buck Up My Data", None))
        self.actionRecover_My_Data_from_A_Buckup.setText(_translate("MainWindow", "Load Data from A Buckup", None))
        self.actionUpdate_Local_Search_List.setText(_translate("MainWindow", "Update Local Search List", None))
        self.actionUpdate.setText(_translate("MainWindow", "Update", None))

