# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/ayieko/Projects And  Research/PycharmProjects/Tv-Series-And-Movie-Diary/v2.0/dialogs/addNewTitleDialog.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(349, 196)
        self.stackedWidget = QtGui.QStackedWidget(Dialog)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 351, 151))
        self.stackedWidget.setObjectName(_fromUtf8("stackedWidget"))
        self.page = QtGui.QWidget()
        self.page.setObjectName(_fromUtf8("page"))
        self.groupBox = QtGui.QGroupBox(self.page)
        self.groupBox.setGeometry(QtCore.QRect(10, 0, 331, 148))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 30, 51, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.tvShowTitleEntry = QtGui.QLineEdit(self.groupBox)
        self.tvShowTitleEntry.setGeometry(QtCore.QRect(60, 30, 251, 20))
        self.tvShowTitleEntry.setObjectName(_fromUtf8("tvShowTitleEntry"))
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(60, 70, 51, 21))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.seasonSpin = QtGui.QSpinBox(self.groupBox)
        self.seasonSpin.setGeometry(QtCore.QRect(110, 70, 61, 22))
        self.seasonSpin.setMinimum(1)
        self.seasonSpin.setMaximum(100)
        self.seasonSpin.setObjectName(_fromUtf8("seasonSpin"))
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(60, 110, 51, 21))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.episodeSpin = QtGui.QSpinBox(self.groupBox)
        self.episodeSpin.setGeometry(QtCore.QRect(110, 110, 61, 22))
        self.episodeSpin.setMinimum(1)
        self.episodeSpin.setMaximum(100)
        self.episodeSpin.setObjectName(_fromUtf8("episodeSpin"))
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtGui.QWidget()
        self.page_2.setObjectName(_fromUtf8("page_2"))
        self.groupBox_2 = QtGui.QGroupBox(self.page_2)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 0, 331, 148))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.label_4 = QtGui.QLabel(self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(10, 30, 51, 16))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.movieTitle = QtGui.QLineEdit(self.groupBox_2)
        self.movieTitle.setGeometry(QtCore.QRect(60, 30, 251, 20))
        self.movieTitle.setObjectName(_fromUtf8("movieTitle"))
        self.label_5 = QtGui.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(10, 60, 71, 21))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.layoutWidget = QtGui.QWidget(self.groupBox_2)
        self.layoutWidget.setGeometry(QtCore.QRect(80, 60, 231, 71))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.todayCheck = QtGui.QRadioButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.todayCheck.sizePolicy().hasHeightForWidth())
        self.todayCheck.setSizePolicy(sizePolicy)
        self.todayCheck.setMinimumSize(QtCore.QSize(91, 21))
        self.todayCheck.setChecked(True)
        self.todayCheck.setObjectName(_fromUtf8("todayCheck"))
        self.verticalLayout.addWidget(self.todayCheck)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.selectDateCheck = QtGui.QRadioButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectDateCheck.sizePolicy().hasHeightForWidth())
        self.selectDateCheck.setSizePolicy(sizePolicy)
        self.selectDateCheck.setObjectName(_fromUtf8("selectDateCheck"))
        self.horizontalLayout_3.addWidget(self.selectDateCheck)
        self.dateEdit = QtGui.QDateEdit(self.layoutWidget)
        self.dateEdit.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dateEdit.sizePolicy().hasHeightForWidth())
        self.dateEdit.setSizePolicy(sizePolicy)
        self.dateEdit.setMinimumSize(QtCore.QSize(101, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.dateEdit.setFont(font)
        self.dateEdit.setObjectName(_fromUtf8("dateEdit"))
        self.horizontalLayout_3.addWidget(self.dateEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.stackedWidget.addWidget(self.page_2)
        self.addButton = QtGui.QPushButton(Dialog)
        self.addButton.setGeometry(QtCore.QRect(250, 160, 75, 31))
        self.addButton.setObjectName(_fromUtf8("addButton"))
        self.layoutWidget1 = QtGui.QWidget(Dialog)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 160, 181, 31))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.tvShowCheck = QtGui.QRadioButton(self.layoutWidget1)
        self.tvShowCheck.setChecked(True)
        self.tvShowCheck.setObjectName(_fromUtf8("tvShowCheck"))
        self.horizontalLayout.addWidget(self.tvShowCheck)
        self.movieCheck = QtGui.QRadioButton(self.layoutWidget1)
        self.movieCheck.setObjectName(_fromUtf8("movieCheck"))
        self.horizontalLayout.addWidget(self.movieCheck)

        self.retranslateUi(Dialog)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.selectDateCheck, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.dateEdit.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Add A New Title Entry", None))
        self.groupBox.setTitle(_translate("Dialog", "Add A New TV Show You Are Seeing.", None))
        self.label.setText(_translate("Dialog", "Title :", None))
        self.tvShowTitleEntry.setPlaceholderText(_translate("Dialog", " Tv Show Title", None))
        self.label_2.setText(_translate("Dialog", "Season :", None))
        self.label_3.setText(_translate("Dialog", "Episode :", None))
        self.groupBox_2.setTitle(_translate("Dialog", "Add A New Movie You Are Seeing.", None))
        self.label_4.setText(_translate("Dialog", "Title :", None))
        self.movieTitle.setPlaceholderText(_translate("Dialog", " Tv Show Title", None))
        self.label_5.setText(_translate("Dialog", "Date Seen : ", None))
        self.todayCheck.setText(_translate("Dialog", "Today.", None))
        self.selectDateCheck.setText(_translate("Dialog", "Select Date : ", None))
        self.addButton.setText(_translate("Dialog", "ADD", None))
        self.tvShowCheck.setText(_translate("Dialog", "Tv Show", None))
        self.movieCheck.setText(_translate("Dialog", "Movie ", None))

